"""Unit tests for media extraction with reference comparison.

This test suite verifies that extracted content matches the reference outputs
generated by extract_test_data.py script.
"""

import pytest
from pathlib import Path
import sys
import json

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))


class TestTextExtractionWithReference:
    """Test text extraction and compare with reference."""
    
    @pytest.mark.unit
    def test_txt_extraction_matches_reference(self):
        """Test that TXT extraction matches reference output."""
        test_file = Path("tests/data/txt/andrew_ng.txt")
        reference_file = Path("tests/data/txt/andrew_ng_extracted.txt")
        
        if not test_file.exists():
            pytest.skip(f"Test file not found: {test_file}")
        
        if not reference_file.exists():
            pytest.skip(f"Reference file not found. Run: python scripts/extract_test_data.py --type text")
        
        # Extract content
        with open(test_file, 'r', encoding='utf-8') as f:
            extracted = f.read()
        
        # Load reference
        with open(reference_file, 'r', encoding='utf-8') as f:
            reference = f.read()
        
        # Compare
        assert extracted == reference, "Extracted content doesn't match reference"
        assert len(extracted) > 0
        assert "Andrew" in extracted
        
        print(f"✅ TXT extraction matches reference ({len(extracted)} chars)")
    
    @pytest.mark.unit
    def test_pdf_extraction_matches_reference(self):
        """Test that PDF extraction matches reference output."""
        test_file = Path("tests/data/pdf/Andrew Ng - Wikipedia.pdf")
        reference_file = Path("tests/data/pdf/Andrew Ng - Wikipedia_extracted.txt")
        
        if not test_file.exists():
            pytest.skip(f"Test file not found: {test_file}")
        
        if not reference_file.exists():
            pytest.skip(f"Reference file not found. Run: python scripts/extract_test_data.py --type text")
        
        try:
            from pypdf import PdfReader
        except ImportError:
            pytest.fail("pypdf library not installed")
        
        # Extract content
        reader = PdfReader(test_file)
        extracted = ""
        for page in reader.pages:
            extracted += page.extract_text()
        
        # Load reference
        with open(reference_file, 'r', encoding='utf-8') as f:
            reference = f.read()
        
        # Compare
        assert extracted == reference, "Extracted content doesn't match reference"
        assert len(extracted) > 0
        assert "Andrew" in extracted
        
        print(f"✅ PDF extraction matches reference ({len(extracted)} chars, {len(reader.pages)} pages)")


class TestImageExtractionWithReference:
    """Test image extraction and compare with reference."""
    
    @pytest.mark.unit
    @pytest.mark.slow
    def test_image_caption_consistency(self):
        """Test that image captioning produces consistent results."""
        test_file = Path("tests/data/img/elon_musk_AI_opinion.jpeg")
        reference_file = Path("tests/data/img/elon_musk_AI_opinion_caption.json")
        
        if not test_file.exists():
            pytest.skip(f"Test file not found: {test_file}")
        
        try:
            from PIL import Image
            from transformers import BlipProcessor, BlipForConditionalGeneration
        except ImportError as e:
            pytest.fail(f"Required library not installed: {e}")
        
        # Load image and generate caption
        image = Image.open(test_file)
        processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
        model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")
        
        inputs = processor(image, return_tensors="pt")
        outputs = model.generate(**inputs, max_new_tokens=50)
        caption = processor.decode(outputs[0], skip_special_tokens=True)
        
        # If reference exists, compare
        if reference_file.exists():
            with open(reference_file, 'r') as f:
                reference = json.load(f)
            
            # Captions should be similar (may not be identical due to model randomness)
            print(f"✅ Image caption generated: '{caption}'")
            print(f"   Reference caption: '{reference['caption']}'")
            
            # Check that both captions are non-empty and similar length
            assert len(caption) > 0
            assert abs(len(caption) - len(reference['caption'])) < 50
        else:
            print(f"⚠️  No reference file found. Caption: '{caption}'")
            print(f"   Run: python scripts/extract_test_data.py --type image")


class TestAudioExtractionWithReference:
    """Test audio extraction and compare with reference."""
    
    @pytest.mark.unit
    @pytest.mark.slow
    def test_audio_transcript_consistency(self):
        """Test that audio transcription produces consistent results."""
        test_file = Path("tests/data/audio/elon-musk-ai-opinion.mp3")
        reference_file = Path("tests/data/audio/elon-musk-ai-opinion_transcript.json")
        
        if not test_file.exists():
            pytest.skip(f"Test file not found: {test_file}")
        
        try:
            import whisper
        except ImportError:
            pytest.fail("whisper library not installed")
        
        # Transcribe audio
        model = whisper.load_model("tiny")  # Use tiny for speed
        result = model.transcribe(str(test_file))
        transcript = result["text"]
        
        # If reference exists, compare
        if reference_file.exists():
            with open(reference_file, 'r') as f:
                reference = json.load(f)
            
            # Transcripts should be similar (may vary slightly)
            print(f"✅ Audio transcript generated ({len(transcript)} chars)")
            print(f"   Reference length: {len(reference['transcript'])} chars")
            print(f"   Transcript preview: {transcript[:100]}...")
            
            # Check that both transcripts are non-empty and similar length
            assert len(transcript) > 0
            # Allow 20% difference in length
            assert abs(len(transcript) - len(reference['transcript'])) < len(reference['transcript']) * 0.2
        else:
            print(f"⚠️  No reference file found. Transcript: {transcript[:100]}...")
            print(f"   Run: python scripts/extract_test_data.py --type audio")


class TestVideoExtractionWithReference:
    """Test video extraction and compare with reference."""
    
    @pytest.mark.unit
    @pytest.mark.slow
    def test_video_metadata_consistency(self):
        """Test that video metadata extraction is consistent."""
        test_file = Path("tests/data/video/elon_musk_ai_danger.mp4")
        reference_file = Path("tests/data/video/elon_musk_ai_danger_extracted.json")
        
        if not test_file.exists():
            pytest.skip(f"Test file not found: {test_file}")
        
        try:
            from moviepy import VideoFileClip
        except ImportError:
            pytest.fail("moviepy library not installed")
        
        # Load video
        video = VideoFileClip(str(test_file))
        
        metadata = {
            "duration": video.duration,
            "size": video.size,
            "fps": video.fps,
            "has_audio": video.audio is not None
        }
        
        video.close()
        
        # If reference exists, compare
        if reference_file.exists():
            with open(reference_file, 'r') as f:
                reference = json.load(f)
            
            # Metadata should match exactly
            assert metadata["duration"] == reference["duration"]
            assert metadata["size"] == reference["size"]
            assert metadata["fps"] == reference["fps"]
            assert metadata["has_audio"] == reference["has_audio"]
            
            print(f"✅ Video metadata matches reference:")
            print(f"   Duration: {metadata['duration']:.2f}s")
            print(f"   Size: {metadata['size']}")
            print(f"   FPS: {metadata['fps']}")
            print(f"   Has audio: {metadata['has_audio']}")
        else:
            print(f"⚠️  No reference file found.")
            print(f"   Run: python scripts/extract_test_data.py --type video")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])

